services:
  redis:
    container_name: redis
    image: redis:7
  backend:
      container_name: backend
      build: "backend/."
      volumes:
        - ./backend:/usr/src/app
      ports:
        - "8000:8000"
      command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      environment:
        - MONGO_URI=mongodb://host.docker.internal:27017/Game
        - REDIS_URI=redis://redis:6379
